site_name: Docstring AI
theme:
  name: material

nav:
  - Home: index.md
  - Config: config.md
  - Chroma DB: chroma.md
  - Docstring Utilites: utils.md
  - GitHub Utilities: gh_utils.md
  - LLM Utilities: llm_utils.md
  - Processes: process.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - "import sys; sys.path.insert(0, '.')"
          options:
            show_source: true
