name: Publish Python Package

on:
  push:
    tags:
      - "v*"  # Trigger this workflow when a new version tag (v1.0.0, etc.) is pushed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"  # Adjust to your supported Python version

    # Install Poetry
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    # Install Dependencies
    - name: Install dependencies
      run: poetry install

    # Build the package
    - name: Build the package
      run: poetry build

    # Publish to PyPI
    - name: Publish to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
        poetry publish --build
