name: Update pyproject.toml Version

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: extract_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update pyproject.toml
        run: |
          sed -i "s/^version = .*/version = \"${{ env.VERSION }}\"/" pyproject.toml

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add pyproject.toml
          git commit -m "Update version to ${{ env.VERSION }}"
          git push
